### ISSUE TITLE
Scorecards does not recognize Dependabot

### ISSUE THREAD

**Issue by behnazh** [jenstroeger/python-package-template#106]
Tracking issue for:
- [ ] https://github.com/jenstroeger/python-package-template/security/code-scanning/1

I believe this is due to [the recent change](https://github.com/jenstroeger/python-package-template/pull/97/commits/c9b22ce91e4352f91ce879cba5a8471da8205934) of `.yml` to `.yaml` files.

**Comment by jenstroeger** [comment]
Dang… and sigh. Un-rename these files, then?

**Comment by behnazh** [comment]
I've opened a [PR](https://github.com/ossf/scorecard/pull/1601) in Scorecard. Let's see how that goes.

**Comment by behnazh** [comment]
Scorecard will support `.github/dependabot.yaml` via this merged [PR](https://github.com/ossf/scorecard/pull/1601).
