### ISSUE TITLE
Generate Github/Markdown documentation.

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#117]
Currently this repository is set up to use [Sphinx](https://www.sphinx-doc.org/en/master/) to build HTML documentation (or whichever other output format [Sphinx provides](https://www.sphinx-doc.org/en/master/usage/builders/index.html)). Considering this repo is hosted on Github, I think it follows naturally that we should be able to generate documentation in Markdown and publish the generated documentation here… 🤔

There are a few tools that generate Markdown from Python docstrings, with or without Sphinx ([older Stackoverflow question](https://stackoverflow.com/questions/13396856/markdown-output-for-sphinx-based-documentation)):
- [NiklasRosenstein/pydoc-markdown](https://github.com/NiklasRosenstein/pydoc-markdown)
- [ml-tooling/lazydocs](https://github.com/ml-tooling/lazydocs)
- [clayrisser/sphinx-markdown-builder](https://github.com/clayrisser/sphinx-markdown-builder)
- [mkdocs/mkdocs/](https://github.com/mkdocs/mkdocs/)

It would then make sense to integrate a “generate documentation” step into our [release Action](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/check-and-release-main.yaml), and either find a way to publish the generated Markup directly into the repository or as a [Github Wiki](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis) (which is its own repo), or use e.g. the [uibcdf/action-sphinx-docs-to-gh-pages](https://github.com/uibcdf/action-sphinx-docs-to-gh-pages) Action to publish to [Github Pages](https://pages.github.com/).

Lastly, perhaps it would also make sense for this repository to opine/dictate a docstring style (e.g. based on [Google’s Style Guide](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings)) and check docstrings using Sphinx’s [Napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/) extension)?

**Comment by brad-getpassport** [comment]
Making it easy to get to the documentation, like auto-generate and push to the Github Wiki would be great imho.

**Comment by jenstroeger** [comment]
See also the [sphinx-notes/markdown-builder](https://github.com/sphinx-notes/markdown-builder) fork of the original [sphinx-markdown-builder](https://github.com/clayrisser/sphinx-markdown-builder) (background in issue https://github.com/clayrisser/sphinx-markdown-builder/issues/59).

**Comment by jenstroeger** [comment]
PR https://github.com/jenstroeger/python-package-template/pull/224 is now open.

**Comment by jenstroeger** [comment]
PR https://github.com/jenstroeger/python-package-template/pull/396, commit https://github.com/jenstroeger/python-package-template/commit/ef0a354185ee42a86308faf0bbe8aba24c2342ba.
