### ISSUE TITLE
Disable mypy incremental mode?

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#195]
By default [`mypy`’s incremental mode](https://mypy.readthedocs.io/en/stable/command_line.html#incremental) is enabled, which writes a cache of previous evaluation results. In our Makefile we wipe that cache with `make clean`

https://github.com/jenstroeger/python-package-template/blob/4f156fe9cce93eaf9094a2db954ff6344334aea4/Makefile#L118-L120

Stale cached values have been biting me and others several times now, and I’m tempted to _disable_ incremental mode by default in our [mypy.ini](https://github.com/jenstroeger/python-package-template/blob/main/mypy.ini):
```ini
[mypy]
incremental=False
```

Thoughts? 🤔

**Comment by brad-getpassport** [comment]
@jenstroeger This isn't an issue imho.  Since the github actions are never really doing this, they are always `clean builds` disabling incremental is effectively ensuring you are always building what the github actions will build.

**Comment by jenstroeger** [comment]
@brad-getpassport I’ve noticed this issue with local development: for example if the code stays the same but I update another package that my code depends on then `mypy` doesn’t pick up that change and begins to find “errors” where there aren’t any.

I agree that in CI this flag would have no impact because every Action starts with an empty cache anyway.

**Comment by jenstroeger** [comment]
PR #197 and commit https://github.com/jenstroeger/python-package-template/commit/5149ddf0e599a8df237c1f4d91511c005c4272d9.
