### ISSUE TITLE
Migrate from setup.py to pyproject.toml

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#202]
We currently use a [setup.py](https://github.com/jenstroeger/python-package-template/blob/main/setup.py) file to store package metadata and installation information. However, as the [`pip` documentation mentions](https://pip.pypa.io/en/stable/reference/build-system/setup-py/):

> Prior to the introduction of pyproject.toml-based builds (in [PEP 517](https://peps.python.org/pep-0517/) and [PEP 518](https://peps.python.org/pep-0518/)), pip had only supported installing packages using setup.py files that were built using [setuptools](https://pypi.org/project/setuptools/). The interface documented here is retained currently solely for legacy purposes, until the migration to pyproject.toml-based builds can be completed.

And from issue https://github.com/slsa-framework/slsa-github-generator/issues/55:

> I think it's really our only option. We can do some things to guess the build backend that needs to be present, but it's not guaranteed to be correct, or capture all bulid-time dependencies. Instead, pyproject.toml is the standardized way to do this. I think it would be reasonable to say we only support building projects that specify pyproject.toml.

Let’s move on then, and move to [pyproject.toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/). For inspiration, @hynek has moved the [**structlog** package to pyproject.toml](https://github.com/hynek/structlog/blob/main/pyproject.toml) (and uses [Flit](https://flit.pypa.io/) instead of [Setuptools](https://setuptools.pypa.io/en/latest/)).

And while we’re at it:
- Let’s [merge](https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml) the [mypy.ini](https://github.com/jenstroeger/python-package-template/blob/main/mypy.ini) file into pyproject.toml as well?
- Let’s [merge](https://pylint.pycqa.org/en/latest/user_guide/run.html#command-line-options) the [pylintrc](https://github.com/jenstroeger/python-package-template/blob/main/pylintrc) file into pyproject.toml as well?
- Unfortunately, `flake8` does not (yet?) support pyproject.toml (see also issue https://github.com/PyCQA/flake8/issues/234).
- Unfortunately, our PR Commit Lint Action does not (yet?) support pyproject.toml (see also issue https://github.com/CondeNast/conventional-pull-request-action/issues/15).

**Comment by behnazh** [comment]
>And while we’re at it:
    Let’s [merge](https://mypy.readthedocs.io/en/stable/config_file.html) the [mypy.ini](https://github.com/jenstroeger/python-package-template/blob/main/mypy.ini) file into pyproject.toml as well?
    Let’s [merge](https://pylint.pycqa.org/en/latest/user_guide/run.html#command-line-options) the [pylintrc](https://github.com/jenstroeger/python-package-template/blob/main/pylintrc) file into pyproject.toml as well?
    Unfortunately, flake8 does not (yet?) support pyproject.toml (see also issue https://github.com/PyCQA/flake8/issues/234).

Agreed. It would be nice to have all the configurations in `pyproject.toml` if possible.

**Comment by jenstroeger** [comment]
Commit https://github.com/jenstroeger/python-package-template/commit/be7ba064192624558fbf97c2dea37a7189ccb3ad.
