### ISSUE TITLE
Actions execute again on Semantic Release

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#222]
When merging into `main` then all Actions fire up, including the [Semantic Release](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/check-and-release-main.yaml) action. That then creates a new `bump:` commit and pushes that commit to `main` — which then fires up all Actions _again_.

Take a look at [these Actions](https://github.com/jenstroeger/python-package-template/actions) triggered by commit https://github.com/jenstroeger/python-package-template/commit/db56423ded764c39afbe6b00de730b53bf3d6c08: 

![actions](https://user-images.githubusercontent.com/12053937/174535011-46032ce3-daca-4499-a1a2-30d9d79a0cfb.jpg)

First, commit db56423 triggers the [CodeQL](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/codeql-analysis.yaml), [Scorecard](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/scorecards-analysis.yaml), and [Check & Release](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/check-and-release-main.yaml) actions, the latter pushing commit 174485c which in turn triggers these three Actions _again_.

I think we could prevent this from happening by adding `[skip actions]` (or some such, see [docs](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/)) to the release commit:

https://github.com/jenstroeger/python-package-template/blob/174485ce6115341a4061ddec9f46147b0c19cd3f/pyproject.toml#L161

**Comment by behnazh** [comment]
Adding `[skip actions]` to the release commit sounds good to me. The only issue would be running semantic release locally where the `commitizen` pre-commit hook would fail:

```
semantic-release version
...
error: Check conventional commit message........................................Failed
error: - hook id: commitizen
error: - exit code: 14
error: 
error: commit validation: failed!
error: please enter a commit message in the commitizen format.
error: commit "": "[skip ci] bump: release v1.6.0
error: 
error: Automatically generated by python-semantic-release"
error: pattern: (build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:(\s.*)
```

**Comment by jenstroeger** [comment]
@behnazh what about adding it at the end of the commit message? That’s how we handle Jira ticket references too:
```
bump: v1.5.0 [skip actions]
```

**Comment by behnazh** [comment]
I've added the change to the [CI refactoring PR](https://github.com/jenstroeger/python-package-template/pull/211) because it's a CI change.
See [eea528c](https://github.com/jenstroeger/python-package-template/pull/211/commits/eea528c6cd63298fafe6b35c2975394b5feb7193).

**Comment by jenstroeger** [comment]
Commit https://github.com/jenstroeger/python-package-template/commit/43087880c093a45333e66e2400343e651e5e7c51.

**Comment by jenstroeger** [comment]
@behnazh that worked 👍🏼

![actions](https://user-images.githubusercontent.com/12053937/174914270-834d7251-d17c-47ae-8d15-119c0242580e.jpg)

**Comment by jenstroeger** [comment]
Perhaps something like this:
```yaml
if: "!contains(github.event.commits[0].message, '[skip actions]')"
```
That would still run the [CodeQL](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/codeql-analysis.yaml), [Scorecard](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/scorecards-analysis.yaml), and [Check & Release](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/check-and-release-main.yaml) Actions though on that one new commit. Would that matter? Or does the green ✓ matter more?

**Comment by behnazh** [comment]
> Actions run Node, right? So could we be more precise using [str.startsWith()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith)?

Have you tried `if: !startsWith(github.event.commits[0].message, 'bump:')`?

You can add it to the [release job](https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/check-and-release-main.yaml#L15) to avoid running the release again.

**Comment by jenstroeger** [comment]
So this works:
```yaml
  release:
    needs: check
    name: Release
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.commits[0].message, 'bump:')"
 ```
Which means that all other jobs still run on that one single release commit…

**Comment by jenstroeger** [comment]
Commit https://github.com/jenstroeger/python-package-template/commit/a86ad65721683f7219b49900b2d1989bed3c0201.

**Comment by jenstroeger** [comment]
@behnazh I think we’re good now:

![actions-1](https://user-images.githubusercontent.com/12053937/175475340-3250a1ae-2174-4b97-9fe0-0fa42ca8137a.jpg)

Commit https://github.com/jenstroeger/python-package-template/commit/d15416973b3bd800b11960803ab82b1dbdc1c35d triggers all three Action workflows and the Check & Release Action ([run](https://github.com/jenstroeger/python-package-template/actions/runs/2553872530)) pushes the release commit https://github.com/jenstroeger/python-package-template/commit/44be5ac339ae07965b4fc99eaa4f5756d0c79132. That release commit triggers, again, all three Actions except that the Release job _does not_ run this time around ([run](https://github.com/jenstroeger/python-package-template/actions/runs/2553905738)):

![actions-2](https://user-images.githubusercontent.com/12053937/175475668-3d958a33-5a97-4118-ba6f-50e15aef891e.jpg)

And we even have our green checkmark back:

![actions-3](https://user-images.githubusercontent.com/12053937/175476226-21c74f3d-53d5-4a70-8d62-32373e0a4f09.jpg)
