### ISSUE TITLE
Fix code scanning alert - Security-Policy

### ISSUE THREAD

**Issue by behnazh** [jenstroeger/python-package-template#228]
Tracking issue for:
- [ ] https://github.com/jenstroeger/python-package-template/security/code-scanning/36

I suspect Scorecards does not recognize the [symbolic link](https://github.com/jenstroeger/python-package-template/blob/main/SECURITY.md) to [UPSTREAM_SECURITY.md](https://github.com/jenstroeger/python-package-template/blob/main/UPSTREAM_SECURITY.md).

**Comment by jenstroeger** [comment]
PR https://github.com/jenstroeger/python-package-template/pull/245, commit https://github.com/jenstroeger/python-package-template/commit/e64554bc313f5860684f5b8949bdd0b86e472b8e.
