### ISSUE TITLE
Move `.upgraded` helper file into the virtual environment

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#240]
Our Makefile uses a `.upgraded` file to indicate when/if the venv has been upgraded:

https://github.com/jenstroeger/python-package-template/blob/66347c69af6dd9c30b2b85ebe022d2844573faee/Makefile#L56-L60

I think the file should live in `${VIRTUAL_ENV}/.upgraded` instead of the repo’s root, because it’s concerned with the venv only and removing the venv folder manually wouldn’t leave behind that now-stale file.

**Comment by behnazh** [comment]
Sounds good :+1:

**Comment by jenstroeger** [comment]
PR https://github.com/jenstroeger/python-package-template/pull/248, commit https://github.com/jenstroeger/python-package-template/commit/2a24e248a543f5e58020a7b522c73adbc3271d47.
