### ISSUE TITLE
After pushing and tagging a release commit, `build.yaml` should rebase the staging branch on top of main.

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#266]
For details, see https://github.com/jenstroeger/python-package-template/pull/259#discussion_r931588071.

**Comment by jenstroeger** [comment]
As per linked comment:

> This (change) would hardwire the branch name `staging` into the process, though, and maybe we should make it configurable (somewhat related to https://github.com/jenstroeger/python-package-template/pull/259#discussion_r924000223)?

I’m ok with using `staging` in the Action itself, and then document in the README that users may want to change that branch name. I’ve seen `develop` or `beta` used in the same scenario.

**Comment by jenstroeger** [comment]
So I think we want to add another step after this one:

https://github.com/jenstroeger/python-package-template/blob/25c486b68d04c813c9bd366b44db858e20d281e4/.github/workflows/release.yaml#L57-L60

For example
```yaml
     - name: Rebase staging branch 
       run: | 
         git checkout staging
         git rebase main
         git push
```
We’ve already checked out all branches a few steps before:

https://github.com/jenstroeger/python-package-template/blob/25c486b68d04c813c9bd366b44db858e20d281e4/.github/workflows/release.yaml#L36-L40

**Comment by behnazh** [comment]
Sounds fine with me. But before merging that we should investigate this whole branch protection vs automatic release through pull requests to make sure the histories would be in sync. At least we should understand why it's not working as we want in GitHub.

**Comment by jenstroeger** [comment]
There’s also this problem: what if the `git rebase main` fails because of conflicts? The chance is slim, but still somebody may have merged new commits into `staging` while the Release workflow was checking the new release…

**Comment by jenstroeger** [comment]
PR #536, commit https://github.com/jenstroeger/python-package-template/commit/7d9f0a4619bd505ca4100ef0db495c0c11534309.
