### ISSUE TITLE
Change credentials for Actions user

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#280]
We currently use these credentials

https://github.com/jenstroeger/python-package-template/blob/c7541754294c634cd807068ffaf37bd0279cbb52/.github/workflows/build.yaml#L21-L22

to create and push a bump commit:

https://github.com/jenstroeger/python-package-template/blob/c7541754294c634cd807068ffaf37bd0279cbb52/.github/workflows/build.yaml#L76-L78

Which yields this commit:
```log
commit c7541754294c634cd807068ffaf37bd0279cbb52 (HEAD -> main, tag: v2.2.0, origin/main, origin/HEAD)
Author: github-actions <github-actions@github.com>
Date:   Sun Jul 31 03:47:56 2022 +0000

    bump: release 2.1.0 → 2.2.0

```
and Github then doesn’t associate a user with it:

![github](https://user-images.githubusercontent.com/12053937/184557975-caad8d3f-50c6-4ee7-95d0-1e6c0935546f.jpg)

I wasn’t able to find a definite suggestion in the Github documentation, but it looks like [actions-user](https://github.com/actions-user) is available and used by other frameworks. It’s also the same user that [python-semantic-release](https://github.com/relekang/python-semantic-release) Action used (still does) before we replaced it with tailored code:

![github-actions-user](https://user-images.githubusercontent.com/12053937/184558060-122b5ad8-a1f8-4c1f-9101-cd729bd63c25.jpg)

@behnazh perhaps we should use that user name instead, considering this repo isn’t part of an org which can have a dedicated devops account? Related conversation is https://github.com/relekang/python-semantic-release/issues/473#issue-1308812021

**Comment by behnazh** [comment]
How about using your own username? Ideally this should be devops username though. It would be good to document that.

**Comment by jenstroeger** [comment]
So we want to abandon using that `actions-user` altogether? That probably makes sense, it doesn’t belong to this repo and we have no credentials for it.

**Comment by jenstroeger** [comment]
PR https://github.com/jenstroeger/python-package-template/pull/295, commit https://github.com/jenstroeger/python-package-template/commit/53edbe284b55dc604640da825694a377ee8f71bf now gives us

![bump](https://user-images.githubusercontent.com/12053937/186831501-b75ca196-8069-4ca6-9ea0-1d5837e5c691.jpg)
