### ISSUE TITLE
Release Action fails if there are no tags in a repository

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#301]
This line

https://github.com/jenstroeger/python-package-template/blob/f602cb4d81012453212cb3017a8ae2549347a4eb/.github/workflows/release.yaml#L58

can break the workflow if there are no tags set for a repository: the [`--incremental`](https://commitizen-tools.github.io/commitizen/changelog/#incremental) option seems to require a tag:
```
> git tag
> cz changelog --dry-run --incremental --unreleased-version "Release Notes" 
No tag found to do an incremental changelog
```
A workaround would be
```bash
if [ -z "`git tag`" ]; then \
  cz changelog --dry-run --unreleased-version "Release Notes" > dist/RELEASE_NOTES.md; \
else \
  cz changelog --dry-run --incremental --unreleased-version "Release Notes" > dist/RELEASE_NOTES.md; \
fi
 ```
although I’d prefer to solve this on `commitizen`’s side, for example by allowing `--incremental` without tags in which case the entire log should be considered. @Lee-W or @Woile, what do you think?

Somewhat related issues with the same error are https://github.com/commitizen-tools/commitizen/issues/297, https://github.com/commitizen-tools/commitizen/issues/463, https://github.com/commitizen-tools/commitizen/issues/529

**Comment by Woile** [comment]
It would make sense indeed. Do you have some time to send a PR?
I was wondering, in your case gha, shouldn't you run `cz bump --changelog`?

**Comment by jenstroeger** [comment]
> It would make sense indeed. Do you have some time to send a PR?

@Woile I can take a stab at it, if you’d like.

> […] shouldn't you run `cz bump --changelog`?

I think we run

https://github.com/jenstroeger/python-package-template/blob/f602cb4d81012453212cb3017a8ae2549347a4eb/.github/workflows/release.yaml#L58

to generate the Release Notes which contain only the changes of the current release (i.e. since the last tag), and then we run

https://github.com/jenstroeger/python-package-template/blob/f602cb4d81012453212cb3017a8ae2549347a4eb/.github/workflows/release.yaml#L60-L61

right after to update the actual changelog and bump the version. @behnazh has probably more to say here. @Woile, I think you’re suggesting to consolidate those two lines into a single `cz` call?

**Comment by Woile** [comment]
> @Woile I can take a stab at it, if you’d like.

Thanks, that'd be useful. I think it should only fail if there's nothing to generate.

> I think you’re suggesting to consolidate those two lines into a single cz call?

In commitizen there are some docs explaining [how to do a release](https://commitizen-tools.github.io/commitizen/tutorials/github_actions/) with our github action. 

But nowadays you also have some alternatives like [this](https://commitizen-tools.github.io/commitizen/bump/#-changelog-to-stdout) or doing this:
```
cz bump
cz changelog --dry-run $(cz version --project) > dist/RELEASE_NOTES.md
```

**Comment by behnazh** [comment]
>shouldn't you run cz bump --changelog?

> But nowadays you also have some alternatives like [this](https://commitizen-tools.github.io/commitizen/bump/#-changelog-to-stdout) or doing this:
> 
> ```
> cz bump
> cz changelog --dry-run $(cz version --project) > dist/RELEASE_NOTES.md
> ```

Thanks @Woile . Both suggestions make sense after doing a bit of refactoring :+1:

**Comment by jenstroeger** [comment]
PR #303, commit https://github.com/jenstroeger/python-package-template/commit/c755a0913c9f07e531526bb4fbde709d43c4d626.
