### ISSUE TITLE
Consider adding a .gitattributes file.

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#389]
Based on [this conversation](https://github.com/jenstroeger/python-package-template/pull/388#issuecomment-1319592490) with @thbeu we should consider adding a [`.gitattributes`](https://www.git-scm.com/docs/gitattributes) file for better control over e.g. file endings and large file management.

**Comment by jenstroeger** [comment]
@thbeu would you like to add that file and open a PR?

**Comment by thbeu** [comment]
Sure. Can do.

**Comment by jenstroeger** [comment]
Commit https://github.com/jenstroeger/python-package-template/commit/c56f95291db98afc57d8539f7b8b03734a9c50af.
