### ISSUE TITLE
Rename `master` branch to `main`.

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#44]
There’s been much discussion around changing the branch name `master` to `main` (e.g. [here](https://sfconservancy.org/news/2020/jun/23/gitbranchname/)) and Github makes that [fairly easy](https://github.com/github/renaming#renaming-existing-branches). Shall we?

**Comment by behnazh** [comment]
Good idea!

**Comment by bradgetpassport** [comment]
seconded.

**Comment by bradgetpassport** [comment]
second!

**Comment by jenstroeger** [comment]
@behnazh and @bradgetpassport — I renamed the `master` branch to `main`. If you have a local clone of this repo, please take a look at the [Updating a local clone after a branch name changes](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes) instructions.

**Comment by DushkoTasevski** [comment]
@jenstroeger Just a reminder, next version of the update should take care of the rename inside the Github Actions's `check-and-release-main.yml` file too.

**Comment by jenstroeger** [comment]
Thanks @DushkoTasevski, see PR https://github.com/jenstroeger/python-package-template/pull/72.
