### ISSUE TITLE
Building local docker image needs to clean dist folder

### ISSUE THREAD

**Issue by dushko-getpassport** [jenstroeger/python-package-template#480]
Running the ``make docker-build`` from any servicer repo, if the dist is not deleted it recreates old image (doesn't contain the new code), although it looks like the command ran successfully.

Also if possible, the step of installing the python venv often fails with 401 error, although ``make login-sso`` has just been ran. Still need to clean the whole venv and just reinstall (``make upgrade`` doesn't help). Probably is some cache issue somewhere

**Comment by jenstroeger** [comment]
> Running the `make docker-build` from any servicer repo, if the dist is not deleted it recreates old image (doesn't contain the new code), although it looks like the command ran successfully.

@dushko-getpassport running `make dist` twice builds both the binary and the source distribution with each run, and modifications to the source were picked by that second run.

I might need more log information to understand what’s going on.

> Also if possible, the step of installing the python venv often fails with 401 error, although `make login-sso` has just been ran. Still need to clean the whole venv and just reinstall (`make upgrade` doesn't help). Probably is some cache issue somewhere

Pulling from a private PyPI server (e.g. an [AWS hosted artifactory](https://aws.amazon.com/codeartifact/)) is outside of the scope of this repo. I suggest raising this issue internally with your coworkers.

Closing the issue on this public repository, looks like both aspects are better addressed internally at your company 🤓
