### ISSUE TITLE
Should we consider `.pyi` files at all?

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#494]
Packages can inline type annotations into the code, or they can use [`.pyi` stub files](https://peps.python.org/pep-0484/#stub-files) to add type annotations for existing `.py` files.

We’ve not considered the latter and perhaps it would make sense to add the [flake8-pyi](https://github.com/PyCQA/flake8-pyi) plugin for those users who do?

**Comment by behnazh** [comment]
> We’ve not considered the latter and perhaps it would make sense to add the [flake8-pyi](https://github.com/PyCQA/flake8-pyi) plugin for those users who do?

Sure, sounds good.

**Comment by jenstroeger** [comment]
PR #512 commit https://github.com/jenstroeger/python-package-template/commit/e433a9ab7dd1a88128918c676f60637881710241.
