### ISSUE TITLE
Add actionlint for GitHub Actions workflows

### ISSUE THREAD

**Issue by behnazh** [jenstroeger/python-package-template#58]
I came across a [linter for GitHub Actions](https://github.com/rhysd/actionlint). It would be good to add it both as a `pre-commit` hook and as a CI check. I couldn't find an [existing `pre-commit` hook ](https://pre-commit.com/hooks.html)for it and might need to create a local hook.

**Comment by jenstroeger** [comment]
Very much agree, but I dislike the [go](https://go.dev/) dependency — although I do have it installed locally.

I wonder if @asottile would accept a PR for the [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks) repository with such a hook 🤔

**Comment by asottile** [comment]
pre-commit-hooks aims to be language/tooling agnostic where possible -- I think such a tool would be too specific

**Comment by jenstroeger** [comment]
I think a related hook is the [check-jsonschema](https://github.com/sirosen/check-jsonschema) hook.

**Comment by jenstroeger** [comment]
@behnazh I think your PR https://github.com/jenstroeger/python-package-template/pull/505 closes this issue, too?
