### ISSUE TITLE
Fix semantic-release tool inconsistency.

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#62]
We have specified this dependency:

https://github.com/jenstroeger/python-package-template/blob/b36c1d0e3cd288635fc16442f5c848b4abff3a9a/setup.py#L63

whereas the Github action uses this one:

https://github.com/jenstroeger/python-package-template/blob/b36c1d0e3cd288635fc16442f5c848b4abff3a9a/.github/workflows/check-and-release-main.yml#L44

So, the locally installed [semantic-release tools](https://github.com/relekang/python-semantic-release) may not match the ones used by the Action when running a CI workflow.

I think there are several ways of addressing this:

1. Pin the Github Action to the same version as specified by `setup.py`. That’ll introduce duplication, though, and feels tedious.
2. Remove the dependency from `setup.py` because the tools aren’t used often locally; if they are, a manual installation may suffice.
3. Tools like [act](https://github.com/nektos/act) may be a good replacement for 2 while ensuring a single point of specifying that dependency.

Thoughts?

**Comment by behnazh** [comment]
I'm all for having a single source of truth.I would vote for removing the dependency from the `setup.py` if the intention is to use semantic-release locally.  [act](https://github.com/nektos/act) indeed sounds interesting for locally replicating the actions, and using actions as the source of truth.

**Comment by jenstroeger** [comment]
And while we’re talking about potential inconsistencies:

https://github.com/jenstroeger/python-package-template/blob/b36c1d0e3cd288635fc16442f5c848b4abff3a9a/setup.py#L59

and

https://github.com/jenstroeger/python-package-template/blob/b36c1d0e3cd288635fc16442f5c848b4abff3a9a/.pre-commit-config.yaml#L64-L65

Here, I’m tempted to use the locally installed `mypy`, just like we do with `pylint` and `tox`:

https://github.com/jenstroeger/python-package-template/blob/b36c1d0e3cd288635fc16442f5c848b4abff3a9a/.pre-commit-config.yaml#L52-L59

**Comment by behnazh** [comment]
> I’m tempted to use the locally installed mypy, just like we do with pylint and tox:

Sounds like a good idea. I would vote for removing the [external mypy pre-commit hook](https://github.com/pre-commit/mirrors-mypy) altogether, as it's causing lots of problems.

I would keep the `pre-commit` dependency in `setup.py` and pin it (again for reproducibility and preparing for SLSA compliance).

**Comment by jenstroeger** [comment]
> Sounds like a good idea. I would vote for removing the [external mypy pre-commit hook](https://github.com/pre-commit/mirrors-mypy) altogether, as it's causing lots of problems.

See PR https://github.com/jenstroeger/python-package-template/pull/65. Note that that change also removed the duplicated package dependencies 👍🏼
 
> I would keep the `pre-commit` dependency in `setup.py` and pin it (again for reproducibility and preparing for SLSA compliance).

…which means that the local `pre-commit` would shadow a globally installed `pre-commit` of a possibly different version. May never matter, though.
