### ISSUE TITLE
Moving towards SLSA Level 1.

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#69]
@behnazh, if I understand you correctly in related issue https://github.com/jenstroeger/python-package-template/issues/25 then we need a [scripted build](https://slsa.dev/requirements#scripted-build) of sorts reach [SLSA Level 1](https://slsa.dev/levels#level-requirements) for this repo. For Python packages (What about applications?) that’s described on the [Creating Built Distributions](https://docs.python.org/3/distutils/builtdist.html) — is that what you mean?

It sounds like the script itself is required, but not the built artifact, e.g.
```bash
#!/usr/bin/env bash

python setup.py bdist
```
which would create e.g. a `dist/package-1.1.2.macosx-10.14-x86_64.tar.gz` artifact; or using the [`sdist`](https://docs.python.org/3/distutils/sourcedist.html) to create a `dist/package-1.1.2.tar.gz` artifact. (See also the [setuptools](https://setuptools.pypa.io/en/latest/userguide/index.html) documentation.)

**Comment by bradgetpassport** [comment]
I would prefer that we utilize a Makefile as it's pretty standard and we can then have:

make distribution
make clean -- to cleanup and start afresh

Also if a package is included it's easy to build as you can just run make

**Comment by behnazh** [comment]
@jenstroeger to reach level 1, the repo needs a scripted build and the [provenance](https://slsa.dev/requirements#available) for the built artifact. Once the build script is added, we can use the [SLSA's existing Action](https://github.com/slsa-framework/github-actions-demo) to generate a provenance in `in-toto` format and upload it as an artifact. The provenance contains the Actions workflow where the build script is run, the `sha256` digest, and other useful metadata.

I agree with @brad-getpassport 's suggestion to use `Makefile`.

**Comment by jenstroeger** [comment]
Thank you for the details, @behnazh. I can open a PR to add a [GNU Makefile](https://www.gnu.org/software/make/manual/html_node/index.html), and we take it from there? Unless you insist on writing it 🤓

**Comment by brad-getpassport** [comment]
@jenstroeger You can also take the makefile I created from the services project.  It's not pretty but does a lot of the setup.

**Comment by jenstroeger** [comment]
PR https://github.com/jenstroeger/python-package-template/pull/74, commit https://github.com/jenstroeger/python-package-template/commit/05f226d53fb7b4ee0bb960754d77bc3d68e3305d. Shipped with [v1.3.0](https://github.com/jenstroeger/python-package-template/releases/tag/v1.3.0) ☺️
